config/routes.rb
Rails.application.routes.draw do
  # --- ユーザー関連 ---
  devise_for :users
  get '/users', to: 'users#index'
  get '/users/:id/show', to: 'users#show_user', as: 'user_show'
  delete '/users/:id/delete', to: 'users#delete_user', as: 'user_delete'
  # フォローフォロワー
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  # --- ロードマップ関連 ---
  # 一覧
  get '/roadmaps', to: 'roadmap_headers#index'
  # 詳細
  get '/roadmaps/:id/show', to: 'roadmap_headers#detail', as: 'roadmap_show'
  # 作成
  get '/roadmaps/new', to: 'roadmap_headers#new', as: 'roadmap_new'
  post '/roadmaps/new', to: 'roadmap_headers#create', as: 'roadmap_create'
  # 編集
  get '/roadmaps/:id/edit', to: 'roadmap_headers#edit', as: 'roadmap_edit'
  patch '/roadmaps/:id/edit', to: 'roadmap_headers#update', as: 'roadmap_update'
  # 削除
  delete '/roadmaps/:id/destroy', to: 'roadmap_headers#destroy', as: 'roadmap_destroy'

  # --- 静的ページ ---
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :roadmap_header, dependent: :destroy
  # ユーザーフォロー
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy, inverse_of: :follower
  has_many :following, through: :active_relationships, source: :followed

  # ユーザーフォロワー
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy, inverse_of: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  validates :name, presence: true, length: { in: 4..20 }
  validates :email, length: { maximum: 254 }
  validates :web_page, length: { maximum: 400 }
  validates :comment, length: { maximum: 400 }
  validates :icon_pass, length: { maximum: 400 }
  validates :admin, inclusion: { in: [true, false] }

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # devise のヘルパー ログイン済みユーザーのみアクセス許可
  before_action :authenticate_user!, only: [:index, :delete_user, :show_user, :following, :followers]
  # 作成者 or 管理者
  before_action :correct_user, only: [:delete_user]

  # ユーザー一覧ページ
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  # ユーザー一覧ページからのユーザー削除
  def delete_user
    @admin = current_user.admin?
    if @admin
      User.find(params[:id]).destroy
      flash[:success] = "User deleted!"
    else
      flash[:error] = "Error not delete"
    end
    redirect_to users_path
  end

  # ユーザー個人ページ
  def show_user
    @current_user_page = params[:id].to_i == current_user.id
    @user = User.find(params[:id])
    @roadmap_headers = RoadmapHeader.where(user: @user).joins("LEFT OUTER JOIN users ON roadmap_headers.user_id = users.id").select("roadmap_headers.*, users.name")
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  # 作成者 or 管理者 以外のユーザーはアクセスできない
  def correct_user
    user_id = User.find(params[:id])
    return if user_id == current_user.id || current_user.admin?

    redirect_to(users_path)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
    <% unless current_user?(@user) %>
      <div id="follow_form">
        <% if current_user.following?(@user) %>
          <%= render 'unfollow' %>
        <% else %>
          <%= render 'follow' %>
        <% end %>
      </div>
    <% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/index.html.erb
<% @title = "All users" %>

<div class="container mt-5">
  <h3 class="h3 text-center mb-5"><i class="fas fa-users light-blue-text"></i> <%= @title %></h3>


  <ul class="list-group mt-3">
    <% @users.each do |user| %>
      <li class="list-group-item">
        <%= link_to user.name, user_show_path(user), class: "text-dark text-underline" %>
        <% if current_user.admin?%>
          <%= link_to user_delete_path(user), data: { confirm: "Delete #{user.name}\nAre you sure?" }, method: :delete, class: "text-dark" do %>
            <i class="far fa-times-circle text-muted"></i>Delete
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div class="apple_pagination">
    <%= will_paginate @users%>
  </div>

</div>

app/views/users/show_follow.html.erb
<div class="container mt-5">
  <h3 class="h3 text-center mb-5"><i class="fas fa-users light-blue-text"></i> <%= @title %></h3>

  <ul class="list-group mt-3">
    <% @users.each do |user| %>
      <li class="list-group-item">
        <%= link_to user.name, user_show_path(user), class: "text-dark text-underline" %>
        <% if current_user.admin?%>
          <%= link_to user_delete_path(user), data: { confirm: "Delete #{user.name}\nAre you sure?" }, method: :delete, class: "text-dark" do %>
            <i class="far fa-times-circle text-muted"></i>Delete
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div class="apple_pagination">
    <%= will_paginate @users%>
  </div>

</div>

app/views/users/show_user.html.erb
<% @title = "#{@user.name}\'s Page" %>

<div class="container mt-5">
  <h3 class="h3 text-center mb-5"><i class="fas fa-user light-blue-text"></i> <%= @title %></h3>
  <div>
    <h4><%= @user.email %></h4>
    <%= render 'follow_form' if user_signed_in? %>
    <p class="grey-text"><%= @user.comment %></p>

    <a href="<%= following_user_path(@user) %>">
      <strong id="following">
        <%= @user.following.count %>
      </strong>
      following
    </a>
    <a href="<%= followers_user_path(@user) %>">
      <strong id="followers">
        <%= @user.followers.count %>
      </strong>
      followers
    </a>

    <% if @current_user_page %>
      <div class="text-right">
        <%= link_to "ロードマップ作成", roadmap_new_path, class: "btn btn-info btn-rounded" %>
        <%= link_to "ユーザー編集", edit_user_registration_path, class: "btn btn-info btn-rounded" %>
        <%= link_to "ログアウト", destroy_user_session_path, class: "btn btn-outline-info btn-rounded waves-effect", method: :delete %>
      </div>
    <% end %>
  </div>

  <div>
    <h4>投稿一覧</h4>
    <%= render 'roadmap_headers/roadmaps' %>
  </div>
</div>