config/routes.rb
Rails.application.routes.draw do
  # --- ユーザー関連 ---
  devise_for :users
  get '/users', to: 'users#index'
  get '/users/:id/show', to: 'users#show_user', as: 'user_show'
  delete '/users/:id/delete', to: 'users#delete_user', as: 'user_delete'
  # フォローフォロワー
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  # --- ロードマップ関連 ---
  # 一覧
  get '/roadmaps', to: 'roadmap_headers#index'
  # 詳細
  get '/roadmaps/:id/show', to: 'roadmap_headers#detail', as: 'roadmap_show'
  # 作成
  get '/roadmaps/new', to: 'roadmap_headers#new', as: 'roadmap_new'
  post '/roadmaps/new', to: 'roadmap_headers#create', as: 'roadmap_create'
  # 編集
  get '/roadmaps/:id/edit', to: 'roadmap_headers#edit', as: 'roadmap_edit'
  patch '/roadmaps/:id/edit', to: 'roadmap_headers#update', as: 'roadmap_update'
  # 削除
  delete '/roadmaps/:id/destroy', to: 'roadmap_headers#destroy', as: 'roadmap_destroy'

  # --- 静的ページ ---
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
end

app/models/roadmap_header.rb
class RoadmapHeader < ApplicationRecord
  belongs_to :user

  # roadmap_detailを１つ所持
  has_one :roadmap_detail, dependent: :destroy

  # デフォルトでcreated_atを逆順でソート
  default_scope -> { order(created_at: :desc) }

  # Formでroadmap_detailを複数所持可能にする
  # allow_destroy : formでdestroyを指定すると子要素を削除する
  # reject_if : すべての入力属性が空の場合、roadmap_detailモデルを作成しない（バリデーションも実行しない）
  #             １つでも属性を入力した場合、roadmap_detailモデルを作成する（バリデーションも実行される）
  accepts_nested_attributes_for :roadmap_detail, allow_destroy: true

  # バリデーション
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 100 }
  validates :assumption_level, length: { maximum: 400 }
end

app/controllers/roadmap_headers_controller.rb
class RoadmapHeadersController < ApplicationController
  # devise のヘルパー ログイン済みユーザーのみアクセス許可
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  # 作成者 or 管理者
  before_action :correct_user, only: [:edit, :update, :destroy]

  # ロードマップ一覧表示
  def index
    @roadmap_headers = RoadmapHeader.joins("LEFT OUTER JOIN users ON roadmap_headers.user_id = users.id").select("roadmap_headers.*, users.name")
  end

  # Roadmapの詳細画面
  def detail
    @roadmap_header = RoadmapHeader.find(params[:id])
    if current_user
      @current_user_roadmap = @roadmap_header.user_id == current_user.id
    end
    @roadmap_details = RoadmapDetail.where(roadmap_header_id: @roadmap_header.id)
  end

  # ロードマップ新規作成画面
  def new
    @roadmap_post = current_user.roadmap_header.build
    @roadmap_post.build_roadmap_detail
  end

  # ロードマップ作成
  def create
    @roadmap_post = current_user.roadmap_header.build(roadmap_header_params)
    if @roadmap_post.save
      flash[:success] = "Created the Roadmap!"
      redirect_to roadmap_show_path(@roadmap_post)
    else
      render "new"
    end
  end

  # ロードマップ編集
  def edit
    @roadmap_post = RoadmapHeader.find(params[:id])
  end

  # ロードマップ更新
  def update
    @roadmap_post = RoadmapHeader.find(params[:id])
    if @roadmap_post.update(roadmap_header_params)
      flash[:success] = "Updated the Roadmap!"
      redirect_to roadmap_show_path(@roadmap_post)
    else
      render "edit"
    end
  end

  # ロードマップ削除
  def destroy
    if RoadmapHeader.find(params[:id]).destroy
      flash[:success] = "Deleted the Roadmap!"
    else
      flash[:alert] = "Error not delete!"
    end
    redirect_to roadmaps_path
  end

  private

  # Strong parameters 不要な情報が入り込まないようにする
  def roadmap_header_params
    # require(:roadmap_header) roadmap_header属性を必須とする
    # permit() 指定された属性を許可する
    params.require(:roadmap_header).permit(:title, roadmap_detail_attributes: [:sub_title, :content])
  end

  # 作成者 or 管理者 以外のユーザーはアクセスできない
  def correct_user
    roadmap_user_id = RoadmapHeader.find(params[:id]).user_id
    return if roadmap_user_id == current_user.id || current_user.admin?

    redirect_to(roadmaps_path)
  end
end

app/helpers/roadmap_headers_helper.rb
module RoadmapHeadersHelper
end

app/views/roadmap_headers/_roadmaps.html.erb
    <ul class="list-group mt-3">
      <% @roadmap_headers.each do |r| %>
        <li class="list-group-item">
          <div>
            <%= link_to r.title, roadmap_show_path(r.id), class: "text-dark text-underline"%>
            <% if user_signed_in? && current_user.admin? %>
              <%= link_to roadmap_destroy_path(r), data: { confirm: "Delete #{r.title}\nAre you sure?" }, method: :delete, class: "text-dark" do %>
                <i class="far fa-times-circle text-muted"></i>Delete
              <% end %>
            <% end %>
          </div>
          <div class="text-muted">
            by <%= link_to r.name, user_show_path(r.user_id), class: "text-muted text-underline" %>
          </div>
        </li>
      <% end %>
    </ul>

app/views/roadmap_headers/detail.html.erb
<% @title = "Detail Roadmap" %>

<div class="container mt-5">
  <h3 class="h3 text-center mb-5"><i class="far fa-map light-blue-text"></i> <%= @title %></h3>

    <% if @current_user_roadmap %>
      <div class="text-right">
        <%= link_to "ロードマップ編集", roadmap_edit_path, class: "btn btn-info btn-rounded" %>
      </div>
    <% end %>

  <h1><%= @roadmap_header.title %></h1>
  <hr>
  <% @roadmap_details.each do |r| %>
    <div class="card">
      <div class="card-header">
        <%= r.sub_title %>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= r.content %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/roadmap_headers/edit.html.erb
<% @title = "Edit Roadmap" %>

<div class="container mt-5">
  <h3 class="h3 text-center mb-5"><i class="far fa-map light-blue-text"></i> <%= @title %></h3>

      <%= form_for(@roadmap_post, url: roadmap_update_path, class: "text-center border border-light p-5" ) do |r| %>
        <%= render "devise/shared/error_messages", resource: @roadmap_post %>

        <%= r.text_field :title, class: "form-control mb-4", placeholder: "タイトル" %>

        <div>
          <%= r.fields_for :roadmap_detail do |rd| %>
            <%= rd.text_field :sub_title, class: "form-control mb-4", placeholder: "サブタイトル" %>

            <div class="field">
              <%= rd.label :content %>
              <%= rd.rich_text_area :content, placeholder: "内容"  %>
            </div>
          <% end %>
        </div>

        <div>
          <%= r.submit @title, class: "btn btn-info btn-block" %>
        </div>
      <% end %>

  <br><br>

  <%= link_to "Delete Roadmap", roadmap_destroy_path(@roadmap_post.id), data: { confirm: "Are you sure?" }, method: :delete,  class: "btn btn-blue-grey waves-effect" %>
</div>

app/views/roadmap_headers/index.html.erb
<% @title = "All Roadmaps" %>

<div class="container mt-5">
  <h3 class="h3 text-center mb-5"><i class="far fa-map light-blue-text"></i> <%= @title %></h3>
  <%= render 'roadmap_headers/roadmaps' %>
</div>

app/views/roadmap_headers/new.html.erb
<% @title = "Create Roadmap" %>

<div class="container mt-5">
  <h3 class="h3 text-center mb-5"><i class="far fa-map light-blue-text"></i> <%= @title %></h3>

      <%= form_for(@roadmap_post, url: roadmap_create_path, class: "text-center border border-light p-5" ) do |r| %>
        <%= render "devise/shared/error_messages", resource: @roadmap_post %>

        <%= r.text_field :title, class: "form-control mb-4", placeholder: "タイトル" %>

        <div>
          <%= r.fields_for :roadmap_detail do |rd| %>
            <%= rd.text_field :sub_title, class: "form-control mb-4", placeholder: "サブタイトル" %>

            <div class="field">
              <%= rd.label :content %>
              <%= rd.rich_text_area :content, placeholder: "内容"  %>
            </div>
          <% end %>
        </div>

        <div>
          <%= r.submit @title, class: "btn btn-info btn-block" %>
        </div>
      <% end %>

</div>