config/routes.rb
Rails.application.routes.draw do
  # --- ユーザー関連 ---
  devise_for :users
  get '/users', to: 'users#index'
  get '/users/:id/show', to: 'users#show_user', as: 'user_show'
  delete '/users/:id/delete', to: 'users#delete_user', as: 'user_delete'
  # フォローフォロワー
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

  # --- ロードマップ関連 ---
  # 一覧
  get '/roadmaps', to: 'roadmap_headers#index'
  # 詳細
  get '/roadmaps/:id/show', to: 'roadmap_headers#detail', as: 'roadmap_show'
  # 作成
  get '/roadmaps/new', to: 'roadmap_headers#new', as: 'roadmap_new'
  post '/roadmaps/new', to: 'roadmap_headers#create', as: 'roadmap_create'
  # 編集
  get '/roadmaps/:id/edit', to: 'roadmap_headers#edit', as: 'roadmap_edit'
  patch '/roadmaps/:id/edit', to: 'roadmap_headers#update', as: 'roadmap_update'
  # 削除
  delete '/roadmaps/:id/destroy', to: 'roadmap_headers#destroy', as: 'roadmap_destroy'

  # --- 静的ページ ---
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
end

app/views/layouts/_footer.html.erb
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">
  <hr class="my-4">

  <!-- Social icons -->
  <div class="pb-4">

    <%# Teitter %>
    <%= link_to "https://twitter.com/amachanprog", target: "_blank" do%>
      <i class="fab fa-twitter mr-3"></i>
    <% end %>

    <%# Blog %>
    <%= link_to "https://amatsukixprog.hatenablog.jp/archive", target: "_blank" do%>
      <i class="fab fa-blogger-b mr-3"></i>
    <% end %>

    <%# github %>
    <%= link_to "https://github.com/amatsukixgithub/study_roadmap", target: "_blank" do%>
      <i class="fab fa-github mr-3"></i>
    <% end %>

    <%= link_to home_path, class: "button" do%>
      Home
    <% end %>

    <%= link_to about_path, class: "button" do%>
      About
    <% end %>

    <%= link_to contact_path, class: "button" do%>
      Contact
    <% end %>

  </div>
  <!-- Social icons -->

  <!--Copyright-->
  <div class="footer-copyright py-3">
    © 2019 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
  </div>
  <!--/.Copyright-->
</footer>
<!--/.Footer-->

app/views/layouts/_header.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark top-nav-collapse">
  <div class="container">

    <!-- Brand -->
    <%= link_to "RoS", about_path, class: "navbar-brand" %>

    <!-- Collapse -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if @title == 'All Roadmaps' %>">
          <%= link_to roadmaps_path, class: "nav-link" do%>
            Articles
          <% end %>
        </li>
        <li class="nav-item <%= 'active' if @title == 'All users' %>">
          <%= link_to users_path, class: "nav-link" do%>
            Users
          <% end %>
        </li>
      </ul>

      <!-- Right -->
      <ul class="navbar-nav nav-flex-icons">

        <% if user_signed_in? %> <!-- ユーザーがログインしているか -->
          <li class="nav-item">
            <%= link_to current_user.name, user_show_path(current_user), class: 'nav-link border border-light rounded waves-effect waves-light' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: 'nav-link' %> <!-- ログイン画面に移行する -->
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: 'nav-link border border-light rounded waves-effect waves-light' %> <!-- 新規登録画面に移行する -->
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<!-- Navbar -->

app/views/layouts/_header_slide.html.erb
  <!-- data-ride="carousel" -->
  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade">

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view">
          <!--Video source-->
          <video class="video-intro" autoplay loop muted>
            <source src="https://assets.mixkit.co/videos/99555/99555-720.mp4" type="video/mp4" />
          </video>
          <%= render 'layouts/header_slide_content' %>
        </div>
      </div>
      <!--/First slide-->

    </div>
    <!--/.Slides-->

  </div>
  <!--/.Carousel Wrapper-->

app/views/layouts/_header_slide_content.html.erb
<!-- Mask & flexbox options-->
<div class="mask rgba-black-light d-flex justify-content-center align-items-center">

  <!-- Content -->
  <div class="text-center white-text mx-5 wow fadeIn">
    <h1 class="mb-4">
      <strong>Roadmap of Study</strong>
    </h1>

    <p>
      <strong>もう迷わない。道筋を立て、新しいことを学ぶ。</strong>
    </p>

    <p class="mb-4 d-none d-md-block">
      <strong>待望のロードマップ共有サイトがここに。今からでも遅くない。「学びたい」全ての人を応援します。</strong>
    </p>
    <% if user_signed_in? %>
      <%= link_to roadmaps_path, class: "btn btn-outline-white btn-lg" do %>
        Go to Roadmaps <i class="fab fa-sketch"></i>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: "btn btn-outline-white btn-lg" do %>
        Sign in <i class="fas fa-sign-in-alt"></i>
      <% end %>
      <%= link_to new_user_registration_path, class: "btn btn-outline-white btn-lg" do %>
        Sign up <i class="fas fa-file-signature"></i>
      <% end %>
    <% end %>
  </div>
  <!-- Content -->

</div>
<!-- Mask & flexbox options-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(@title || '') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>